### ISSUE TITLE
Problem in browserSync.

### ISSUE THREAD

**Issue by smEunus** [Alecaddd/awps#11]
Hi,
In gulp.js file 

`
// Tasks
gulp.task( 'browser-sync', function() {
	browserSync.init({
		proxy: projectURL,
		https: {
			key: '/Users/myusername/.valet/Certificates/wp.dev.key',
			cert: '/Users/myusername/.valet/Certificates/wp.dev.crt'
		},
		injectChanges: true,
		open: false
	});
});
`

where can I find or create `wp.dev.key` and `wp.dev.crt` file?

**Comment by smEunus** [comment]
![screenshot from 2017-12-17 18-34-38](https://user-images.githubusercontent.com/23192502/34079510-2e4c146e-e359-11e7-8c54-88b5b2606f1f.png)

**Comment by smEunus** [comment]
![screenshot from 2017-12-17 18-38-57](https://user-images.githubusercontent.com/23192502/34079529-a43bddda-e359-11e7-9704-022710df02a6.png)
Take a look at this.

**Comment by Alecaddd** [comment]
So, in order to make borwser-sync work in WordPress, you need to set it up properly.
I see that your URL is `personal.dev` but it's not in HTTPS.

You should secure your local domain because Google recently bought the `.dev` domains and made them TLD for them to use internally, so now Chrome automatically redirects every `.dev` to a secure connection.

After your local domain is properly set as HTTPS, to make browsersync work, you need to do these things:

* Update the `.env` file in your WordPress directory to set the `SITE_URL` as `https://personal.dev`
* Update the `gulpfile.js` in your theme and change the `projectURL` variable with your `https://personal.dev`
* Find in your system where are stored your `personal.dev.key` and `personal.dev.cert` (if you're using Valet, the directory should be similar to mine)
* Update the browsersync KEY and CERT in the `gulpfile.js`

Cheers
