### ISSUE TITLE
What is the benefit of the .env file as it is stored in the root directory?

### ISSUE THREAD

**Issue by smEunus** [Alecaddd/awps#12]
wp-config.php and the .env file is in the same directory. 
.env file is hidden and it can be uncovered. So how it is securing my credentials? 

I think my question is not so much clear to you. I just want to figure out if someone has access to my wp-config file he/she can also watch my .env file. So where my security and benefit is?

**Comment by Alecaddd** [comment]
So, I can see you have a bit of confusion here.

First of all, if someone has access to your root folder on your server, it doesn't really matter if you're using the `wp-config.php`, the `.env`, or whatever other methods you could come up with, because you're already screwed!
If a user other than yourself has access to your root folder, it's bad, dangerous, and it doesn't matter how you protect your files, that user is on your server, ENDGAME!

Using the `.env` file has advantages in terms of code collaboration, git commits, manage the same code base on multiple machines, etc.
Let's analyze the most common benefits:

**Code Collaboration**: the `.env` file is ignored by your file browser, your FTP, and Git if you don't specify differently because it's a hidden file. That means you, your friend, your collaborator, your employee, could all work on the same project but having each one of you a different `.env` file that matches the custom settings of each personal machine, without overwriting each others file. Something that constantly happens if using the `wp-config.php`

**Git**: The `.env` file is ignored by Git, that means it doesn't get uploaded to your Git repository.

**Manage multiple servers**: you can set multiple files to act as environmental variables holder based on the type of server you're in. You can have your project with a `.staging`, `.production`, `.beta` file, and dynamically switch those files based on the server your code is currently running.

I suggest you doing some research about the pros and cons of the `.env` file and test some example on your local server.
