### ISSUE TITLE
Is this approach child theme friendly?

### ISSUE THREAD

**Issue by rahulnever2far** [Alecaddd/awps#14]
I have no experience with OOP. I learned PHP while working on WordPress projects and written all my WordPress themes in a procedural manner. I like the modular approach that you have used in this theme. But does it support child themes https://codex.wordpress.org/Child_Themes#Using_functions.php?

**Comment by Alecaddd** [comment]
No, this theme is not built to support child themes, or at least, I haven't tested it for that purpose. This theme is for developers who need a barebone structure to build something from scratch, without relying on preexisting methods or features.
Cheers

**Comment by adampatterson** [comment]
WordPress parent theme usually defines an action that calls a function. You wrap that function in `function_exists()` so that you can overwrite it in a child theme.

```
add_filter('the_title', 'markdown_title');
if ( ! function_exists('markdown_title')) {
    function markdown_title($post_title) {}
}
```
The Child theme simply sets a new function `markdown_title()`

Alternatively, you use OOP in the parent theme and then namespace everything nicely but are now you are using composer autoload in your parent theme and as well as your child theme creating another namespace for that theme and extending parent classes to adjust parent method functionality.

I have not tried this yet, and not many “developer” themes cover this. But because it is namespaced and the scope of the actions and filters are typical `$this` or the namespace of another class.  I would have to use `__construct` to register the actions which then presumably extend, call `parent::__construct();` and hopefully the WordPress actions do their job and use the new method from the child theme. 

```
namespace ParentTheme;
class myClass
{

    public function __construct()
    {
        add_filter('the_title', [$this, 'markdown_title']);
    }

    public function markdown_title($post_title)
    {
        // Make Markdown
    }
}

namespace ChildTheme;
class anotherClass extends myClass {
    public function __construct()
    {
        parent::__construct();
    }
    
    public function markdown_title($post_title)
    {
        // Make Awesome Markdown
    }
}
```

Actually, now that I look at this, I have no idea if it would work.

**Comment by adampatterson** [comment]
Just as a note, if you move what is in `register()` to `__construct()` you can extend your parent theme from a child.
