### ISSUE TITLE
javascript cookie notice

### ISSUE THREAD

**Issue by andreapaiola** [Alecaddd/awps#36]
how can I load css and javascript of this plugin?

https://wordpress.org/plugins/cookie-notice/

https://github.com/dfactoryplugins/cookie-notice/blob/master/cookie-notice.php#L825

@bartoszarendt @lucspe @cristianp6 @chesio

I see the css, but not the js...

**Comment by bartoszarendt** [comment]
most probably your site is missing the wp_footer() function and you don't have js included

**Comment by andreapaiola** [comment]
> most probably your site is missing the wp_footer() function and you don't have js included

thank you, but nope

<img width="258" alt="schermata 2018-09-25 alle 11 44 02" src="https://user-images.githubusercontent.com/16450997/46006693-6a049200-c0b8-11e8-8bca-717b23bb2fd6.png">

![schermata 2018-09-25 alle 11 45 09](https://user-images.githubusercontent.com/16450997/46006747-86a0ca00-c0b8-11e8-83a0-547e0b8bb6e6.png)

**Comment by bartoszarendt** [comment]
please share a link to your site first

**Comment by andreapaiola** [comment]
> please share a link to your site first

sorry, I can't because it's not public

**Comment by andreapaiola** [comment]
ok, it load if I comment

`wp_deregister_script( 'jquery' );`

in the themehttps://github.com/Alecaddd/awps/blob/master/inc/Setup/Enqueue.php

jQuery is a dependency, of course

**Comment by chesio** [comment]
> jQuery is a dependency, of course

WordPress does not output a script, if any of its dependencies is unknown (= not registered), as you just have learned. So why do you deregister jQuery at all? A lot of plugins has scripts that depend on jQuery.

**Comment by Alecaddd** [comment]
I use `wp_deregister_script( 'jquery' );` because WordPress comes with an outdated version and it's always enqueued in the Header and not in the Footer.

I bundle jQuery inside the `webpack.mix.js` file on line 29.

Some plugins have the enqueue option with a dependency listed as the third parameter.
Usually is something like this `array('jquery)`, to let WordPress know that script requires jQuery in order to work.

If you remove the `wp_deregister_script( 'jquery' );` from the `Enqueue.php` file, be sure to comment out the mix autoload to avoid bundling jquery in the compiled assets.
